version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Salah1997
      POSTGRES_DB: FastapiJourney
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
